### ISSUE TITLE
Doesn't work on iPad

### ISSUE THREAD

**Issue by kylefox** [scottjehl/iOS-Orientationchange-Fix#5]
Device: iPad (First generation)
iOS version: 5.0.1

I did some debugging and it looks like the `deviceorientation` event never fires on the iPad. As a result, the `checkTilt` handler never runs and zoom isn't disabled before the device is rotated.

Here's a screenshot immediately after rotating the device to landscape:
http://cl.ly/3X1i38473n1Z023N2f3K

**Comment by vasilisvg** [comment]
I had issues on an iPad 2nd generation with iOs 5.0.1: I couldn't zoom in portrait mode. I was holding the iPad upside down (I was lying in bed) which might be the cause somehow.

**Comment by kylefox** [comment]
I just checked and I'm still able to zoom in portrait mode. I'm not sure how this relates to the original issue I reported, which has to do with the `deviceorientation` event not firing.

**Comment by alexgibson** [comment]
I believe deviceorientation does not fire on the original iPad because it requires a Gyroscope. See ref docs here:

http://developer.apple.com/library/safari/#documentation/SafariDOMAdditions/Reference/DeviceOrientationEventClassRef/DeviceOrientationEvent/DeviceOrientationEvent.html#//apple_ref/doc/uid/TP40010526

**Comment by scottjehl** [comment]
Works pretty well on iPad for me now that it's using devicemotion. Thanks!
